# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  my-executor:
    docker:
    # specify the version you desire here
    - image: circleci/android:api-28-alpha
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew

    - run:
        name: Add Keystore File
        command: echo $keystore | base64 --decode > app/mykeystore

    - run:
        name: Add Google Services File
        command: echo $googleservices | base64 --decode > app/google-services.json

    - run:
        name: Replace Gradle Properties File
        command: echo $gradleprops | base64 --decode > gradle.properties

    - run:
        name: Add Publish Key File
        command: echo $publishkey | base64 --decode > app/my-publish-key.json

    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - run: ./gradlew clean build -x test --info

    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    # Assemble Release
    - run:
        name: Assemble Release
        command: ./gradlew assembleRelease

    - persist_to_workspace:
        # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
        # taken to be the root directory of the workspace.
        root: ~/repo
        paths:
        - build
        - .gradle

  test:
    executor: my-executor
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew

    - run:
        name: Add Keystore File
        command: echo $keystore | base64 --decode > app/mykeystore

    - run:
        name: Add Google Services File
        command: echo $googleservices | base64 --decode > app/google-services.json

    - run:
        name: Replace Gradle Properties File
        command: echo $gradleprops | base64 --decode > gradle.properties

    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    # run tests!
    - run:
        name: Run Tests
        command: ./gradlew lint test

    - store_artifacts:
        path: app/build/reports
        destination: reports

    - store_test_results:
        path: app/build/test-results

  publish:
    executor: my-executor
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - run:
        name: Add Keystore File
        command: echo $keystore | base64 --decode > app/mykeystore

    - run:
        name: Replace Gradle Properties File
        command: echo $gradleprops | base64 --decode > gradle.properties

    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew

    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: ~/repo/build

    - run:
        name: Submit Update To Internal
        command: ./gradlew publishBundle

workflows:
  version: 2.1

  btd:
    jobs:
    - build
    - test:
        requires:
        - build
    - publish:
        filters:
          branches:
            only:
            - develop
            - master
        requires:
        - build
        - test